<%@ Page Language="C#" Title="Студенты" MasterPageFile="~/Site.Master" AutoEventWireup="true" Inherits="WebFormsClient.Students"  CodeBehind="Students.aspx.cs" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><%: Title %></h1>               
            </hgroup>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
   <div style="border-spacing: 10px">     
         <div style="float: left; margin-right: 30px;">
            <asp:DropDownList ID="DropDownList1" runat="server" SelectMethod="GetStudentGroups" AppendDataBoundItems="true" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
            </asp:DropDownList>
            <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" 
                AutoGenerateSelectButton="True" OnSelectedIndexChanged="SelectStudent"
                 DataKeyNames="Id" DeleteMethod="DeleteStudent"
                 UpdateMethod="UpdateStudent" SelectMethod="GetStudents">
                <Columns>
                <asp:BoundField HeaderText="Фамилия" DataField="LastName"/>
                    <asp:BoundField HeaderText="Имя" DataField="FirstName"/>
                    <asp:BoundField HeaderText="Отчество" DataField="MiddleName"/>
                    <asp:BoundField HeaderText="Дата рождения" DataField="DateOfBirth"/>
                    </Columns>
                <SelectedRowStyle BackColor="#00CCFF" />
            </asp:GridView>
        </div>  
        <div style="float: left; margin-right: 30px;">

                <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" AutoGenerateRows="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" 
                    UpdateMethod="UpdateStudent" SelectMethod="SelectSt" OnItemInserted="InsertSt" InsertMethod="InsertStudent">
                    <Fields>
                <asp:BoundField HeaderText="Фамилия" DataField="LastName"/>
                    <asp:BoundField HeaderText="Имя" DataField="FirstName"/>
                    <asp:BoundField HeaderText="Отчество" DataField="MiddleName"/>
                    <asp:BoundField DataField="DateOfBirth" HeaderText="Дата рождения" />
                    </Fields>
                </asp:DetailsView>        
        </div>
  </div>
</asp:Content>

